export interface KenyanInstitution {
  id: string;
  name: string;
  shortName: string;
  type: 'University' | 'TVET/Polytechnic' | 'College' | 'Medical Training' | 'National Poly';
  county: string;
  town: string;
  coordinates: { lat: number; lng: number };
  studentPopulation: number;
  featuredHubs: string[];
  sampleHostelRentRange: string;
  popularServices: string[];
  bannerImage: string;
}

export const KENYAN_CAMPUSES_AND_COLLEGES: KenyanInstitution[] = [
  // --- NAIROBI & METROPOLITAN ---
  {
    id: 'ku_main',
    name: 'Kenyatta University (KU Main Campus)',
    shortName: 'KU Main',
    type: 'University',
    county: 'Kiambu / Nairobi',
    town: 'Kahawa Sukari / Ruiru',
    coordinates: { lat: -1.1812, lng: 36.9275 },
    studentPopulation: 72000,
    featuredHubs: ['Kahawa Sukari Hostels', 'KM Stage Tech Kiosks', 'Ruiru Annex Hub', 'Gate B Printing Zone'],
    sampleHostelRentRange: 'KES 4,500 - 12,000 / mo',
    popularServices: ['Bedsitters', 'Electronics Repair', 'Solar Study Lamps', 'WiFi Hotspots', 'Boda Transport'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'uon_main',
    name: 'University of Nairobi (UoN Main Campus & Chiromo)',
    shortName: 'UoN Main',
    type: 'University',
    county: 'Nairobi',
    town: 'CBD / Chiromo / Parklands',
    coordinates: { lat: -1.2798, lng: 36.8164 },
    studentPopulation: 85000,
    featuredHubs: ['State House Road Hostels', 'Chiromo Science Hub', 'Ngara Student Market', 'CBD Study Hubs'],
    sampleHostelRentRange: 'KES 7,500 - 18,000 / mo',
    popularServices: ['Legal & Medical Books', 'Laptop Repairs', 'Campus Meals', 'Shared Apartments'],
    bannerImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'jkuat_main',
    name: 'Jomo Kenyatta University of Agriculture & Tech (JKUAT)',
    shortName: 'JKUAT Juja',
    type: 'University',
    county: 'Kiambu',
    town: 'Juja',
    coordinates: { lat: -1.0963, lng: 37.0144 },
    studentPopulation: 45000,
    featuredHubs: ['Gate C Student Hub', 'Gate A Tech Corridor', 'Gachororo Village Hostels', 'Highpoint Center'],
    sampleHostelRentRange: 'KES 5,000 - 13,500 / mo',
    popularServices: ['Engineering Components', 'Coding Hubs', 'Solar Panels', 'Electric Scooters', 'Juja Hostels'],
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'mmu_main',
    name: 'Multimedia University of Kenya (MMU)',
    shortName: 'MMU Rongai',
    type: 'University',
    county: 'Kajiado / Nairobi',
    town: 'Ongata Rongai / Magadi Rd',
    coordinates: { lat: -1.3855, lng: 36.7645 },
    studentPopulation: 14000,
    featuredHubs: ['Maasai Lodge Hub', 'Rongai Tuskys Stage', 'Bomas Gateway', 'Tumaini Hub'],
    sampleHostelRentRange: 'KES 6,000 - 14,000 / mo',
    popularServices: ['Media Equipment Rentals', 'Photography Studios', 'Hostels Rongai', 'Fiber WiFi'],
    bannerImage: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'strathmore',
    name: 'Strathmore University',
    shortName: 'Strathmore',
    type: 'University',
    county: 'Nairobi',
    town: 'Madaraka / Ole Sangale',
    coordinates: { lat: -1.3094, lng: 36.8123 },
    studentPopulation: 10000,
    featuredHubs: ['Madaraka Estate Hostels', 'Nairobi West Plaza', 'Mbagathi Way Corridors'],
    sampleHostelRentRange: 'KES 12,000 - 28,000 / mo',
    popularServices: ['Fintech Internships', 'Executive Studio Units', 'MacBook Repairs', 'Catering'],
    bannerImage: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'tuk_main',
    name: 'Technical University of Kenya (TUK)',
    shortName: 'TUK Nairobi',
    type: 'University',
    county: 'Nairobi',
    town: 'CBD / Haile Selassie Ave',
    coordinates: { lat: -1.2917, lng: 36.8267 },
    studentPopulation: 25000,
    featuredHubs: ['Nairobi South B Hostels', 'Ngara Market', 'City Square Workshop Hub', 'Gikomba Tool Center'],
    sampleHostelRentRange: 'KES 5,500 - 11,000 / mo',
    popularServices: ['Welding & Fab Tools', 'Electrical Materials', 'Printing & CAD', 'South B Rooms'],
    bannerImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'kmtc_nairobi',
    name: 'Kenya Medical Training College (KMTC HQ & Nairobi)',
    shortName: 'KMTC Nairobi',
    type: 'Medical Training',
    county: 'Nairobi',
    town: 'KNH Complex, Upper Hill',
    coordinates: { lat: -1.3006, lng: 36.8066 },
    studentPopulation: 18000,
    featuredHubs: ['KNH Commercial Centre', 'Upper Hill Hostels', 'Mbagathi Link', 'Ngumo Estate'],
    sampleHostelRentRange: 'KES 6,500 - 14,000 / mo',
    popularServices: ['Medical Scrubs', 'Stethoscopes & Kits', 'Nursing Revision Packs', 'Hostel Rooms'],
    bannerImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'nairobi_poly',
    name: 'The Kenya National Polytechnic (Nairobi Poly / KNP)',
    shortName: 'Kenya Poly',
    type: 'National Poly',
    county: 'Nairobi',
    town: 'CBD',
    coordinates: { lat: -1.2905, lng: 36.8252 },
    studentPopulation: 20000,
    featuredHubs: ['Machakos Bus Park Hub', 'Industrial Area Attachments', 'River Road Electronics'],
    sampleHostelRentRange: 'KES 4,500 - 9,500 / mo',
    popularServices: ['TVET Equipment', 'Solar Inverter Kits', 'Auto Spares', 'Technical Drawing Gear'],
    bannerImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'cuka_main',
    name: 'Chuka University',
    shortName: 'Chuka Uni',
    type: 'University',
    county: 'Tharaka Nithi',
    town: 'Chuka / Ndagani',
    coordinates: { lat: -0.3292, lng: 37.6444 },
    studentPopulation: 22000,
    featuredHubs: ['Ndagani Market Hub', 'Chuka Town Annex', 'Bypass Hostels'],
    sampleHostelRentRange: 'KES 3,500 - 7,500 / mo',
    popularServices: ['Affordable Bedsitters', 'Farm Produce Direct', 'Student Gas Refills', 'Printing'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'mksu_main',
    name: 'Machakos University',
    shortName: 'Machakos Uni',
    type: 'University',
    county: 'Machakos',
    town: 'Machakos Town',
    coordinates: { lat: -1.5273, lng: 37.2634 },
    studentPopulation: 18000,
    featuredHubs: ['Katoloni Hostels', 'Machakos Town Hub', 'Kyumbi Junction Hub'],
    sampleHostelRentRange: 'KES 3,800 - 8,500 / mo',
    popularServices: ['Hostels Katoloni', 'Solar Battery Stations', 'Laptop Parts', 'Student Groceries'],
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80'
  },

  // --- RIFT VALLEY & WESTERN ---
  {
    id: 'egerton_main',
    name: 'Egerton University (Main Campus Njoro)',
    shortName: 'Egerton Njoro',
    type: 'University',
    county: 'Nakuru',
    town: 'Njoro / Nakuru',
    coordinates: { lat: -0.3689, lng: 35.9329 },
    studentPopulation: 26000,
    featuredHubs: ['Njoro Gate Hostels', 'Njokerio Village', 'Nakuru Town CBD Campus', 'Tatton Agripark'],
    sampleHostelRentRange: 'KES 3,000 - 7,000 / mo',
    popularServices: ['Njokerio Hostels', 'Agri-tech Kits', 'Dairy & Fresh Produce', 'Stationery & Printing'],
    bannerImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'moi_main',
    name: 'Moi University (Main Campus & Eldoret Town)',
    shortName: 'Moi Uni Eldoret',
    type: 'University',
    county: 'Uasin Gishu',
    town: 'Kesses / Eldoret',
    coordinates: { lat: 0.2862, lng: 35.2952 },
    studentPopulation: 38000,
    featuredHubs: ['Talai Centre Hostels', 'Stage Hub Kesses', 'Moi Referral Medical Hub', 'Annex Law Hub'],
    sampleHostelRentRange: 'KES 3,200 - 8,000 / mo',
    popularServices: ['Kesses Hostels', 'Athletic Running Gear', 'Electronics Repaired', 'Solar Lanterns'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'uoeldoret',
    name: 'University of Eldoret (UoE)',
    shortName: 'UoE Chepkoilel',
    type: 'University',
    county: 'Uasin Gishu',
    town: 'Chepkoilel, Eldoret',
    coordinates: { lat: 0.5694, lng: 35.3025 },
    studentPopulation: 20000,
    featuredHubs: ['Chepkoilel Centre', 'Marura Hostels', 'Sogomo Village Hub'],
    sampleHostelRentRange: 'KES 3,000 - 7,500 / mo',
    popularServices: ['Sogomo Hostels', 'Farm Inputs', 'Bicycle & Boda Rentals', 'Groceries'],
    bannerImage: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'maseno_main',
    name: 'Maseno University',
    shortName: 'Maseno Uni',
    type: 'University',
    county: 'Kisumu',
    town: 'Maseno (Equator)',
    coordinates: { lat: 0.0039, lng: 34.6038 },
    studentPopulation: 24000,
    featuredHubs: ['Equator Hostels Hub', 'Siriba Campus Hub', 'Kisumu City CBD Annex', 'Luanda Market'],
    sampleHostelRentRange: 'KES 3,500 - 8,500 / mo',
    popularServices: ['Equator Bedsitters', 'Fish & Tilapia Deliveries', 'Power Bank Charging Hubs', 'WiFi'],
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'mmust_main',
    name: 'Masinde Muliro Univ of Science & Tech (MMUST)',
    shortName: 'MMUST Kakamega',
    type: 'University',
    county: 'Kakamega',
    town: 'Kakamega Town / Kefinco',
    coordinates: { lat: 0.2886, lng: 34.7645 },
    studentPopulation: 25000,
    featuredHubs: ['Kefinco Hostels', 'Sichirai Hub', 'Lurambi Plaza', 'Amalemba Hostels'],
    sampleHostelRentRange: 'KES 3,200 - 7,800 / mo',
    popularServices: ['Kefinco Hostels', 'Solar Lighting Kits', 'Phone Repairs', 'Fresh Organic Greens'],
    bannerImage: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'jooust_main',
    name: 'Jaramogi Oginga Odinga Univ of Sci & Tech (JOOUST)',
    shortName: 'JOOUST Bondo',
    type: 'University',
    county: 'Siaya',
    town: 'Bondo',
    coordinates: { lat: -0.0988, lng: 34.2721 },
    studentPopulation: 16000,
    featuredHubs: ['Bondo Town Center', 'Sinapanga Hostels', 'Usenge Beach Hub'],
    sampleHostelRentRange: 'KES 3,000 - 7,000 / mo',
    popularServices: ['Sinapanga Bedsitters', 'Solar Energy Inverters', 'Lake Fish Supply', 'Internet Hubs'],
    bannerImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'kisii_main',
    name: 'Kisii University',
    shortName: 'Kisii Uni',
    type: 'University',
    county: 'Kisii',
    town: 'Kisii Town / Jogoo',
    coordinates: { lat: -0.6865, lng: 34.7797 },
    studentPopulation: 30000,
    featuredHubs: ['Jogoo Estate Hostels', 'Nyamage Village Hub', 'Kisii CBD Commercial', 'Suneka Hub'],
    sampleHostelRentRange: 'KES 3,500 - 8,000 / mo',
    popularServices: ['Jogoo Hostels', 'Soapstone Crafts', 'Electronics & Phone Fixes', 'Groceries'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'rvtt_nakuru',
    name: 'Rift Valley Technical Training Institute (RVTTI)',
    shortName: 'RVTTI Eldoret',
    type: 'National Poly',
    county: 'Uasin Gishu',
    town: 'Eldoret',
    coordinates: { lat: 0.5143, lng: 35.2698 },
    studentPopulation: 12000,
    featuredHubs: ['Eldoret West Hub', 'Langas Commercial', 'Pioneer Estate Hostels'],
    sampleHostelRentRange: 'KES 3,000 - 6,500 / mo',
    popularServices: ['Carpentry & Masonry Kits', 'Mechanical Tools', 'Student Rooms', 'Printing'],
    bannerImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80'
  },

  // --- COASTAL REGION ---
  {
    id: 'tum_main',
    name: 'Technical University of Mombasa (TUM)',
    shortName: 'TUM Tudor',
    type: 'University',
    county: 'Mombasa',
    town: 'Tudor / Mombasa Island',
    coordinates: { lat: -4.0388, lng: 39.6644 },
    studentPopulation: 22000,
    featuredHubs: ['Tudor Creek Hostels', 'Makupa Market Hub', 'Mwembe Tayari Link', 'Nyali Hub'],
    sampleHostelRentRange: 'KES 5,000 - 12,000 / mo',
    popularServices: ['Ceiling Fans & AC Rooms', 'Marine Engineering Equipment', 'Tudor Hostels', 'Seafood'],
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'pu_main',
    name: 'Pwani University',
    shortName: 'Pwani Uni Kilifi',
    type: 'University',
    county: 'Kilifi',
    town: 'Kilifi Town',
    coordinates: { lat: -3.6264, lng: 39.8499 },
    studentPopulation: 18000,
    featuredHubs: ['Kilifi Bridge Hub', 'Mnarani Hostels', 'Bofa Beach Area', 'Mkoroshoni Center'],
    sampleHostelRentRange: 'KES 4,000 - 9,500 / mo',
    popularServices: ['Solar Fans', 'Mnarani Hostels', 'TukTuk Rides', 'Coconut Produce & Swahili Dishes'],
    bannerImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'mombasa_poly',
    name: 'Kenya Coast National Polytechnic (KCNP)',
    shortName: 'Coast Poly',
    type: 'National Poly',
    county: 'Mombasa',
    town: 'Kisauni / Tudor',
    coordinates: { lat: -4.0456, lng: 39.6622 },
    studentPopulation: 15000,
    featuredHubs: ['Kisauni Lights', 'Bondeni Hub', 'Island Hardware District'],
    sampleHostelRentRange: 'KES 4,500 - 9,000 / mo',
    popularServices: ['Hospitality Tools', 'Electrical Installation Cables', 'Hostels Tudor', 'WiFi'],
    bannerImage: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&auto=format&fit=crop&q=80'
  },

  // --- CENTRAL & MT. KENYA ---
  {
    id: 'dekut_main',
    name: 'Dedan Kimathi University of Technology (DeKUT)',
    shortName: 'DeKUT Nyeri',
    type: 'University',
    county: 'Nyeri',
    town: 'Nyeri / Mweiga Rd',
    coordinates: { lat: -0.3976, lng: 36.9587 },
    studentPopulation: 16000,
    featuredHubs: ['Kimathi Hostels Hub', 'Nyeri Town CBD Hub', 'Coffee Tech Park'],
    sampleHostelRentRange: 'KES 4,000 - 9,000 / mo',
    popularServices: ['Leather & Shoe Tech', 'Solar Microgrid Gear', 'DeKUT Hostels', 'Printing CAD'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'karu_main',
    name: 'Karatina University',
    shortName: 'Karatina Uni',
    type: 'University',
    county: 'Nyeri',
    town: 'Karatina / Kagochi',
    coordinates: { lat: -0.4856, lng: 37.1294 },
    studentPopulation: 13000,
    featuredHubs: ['Kagochi Hostels', 'Karatina Open Market', 'Ishiara Link'],
    sampleHostelRentRange: 'KES 3,200 - 7,200 / mo',
    popularServices: ['Tea & Farm Groceries', 'Student Bedsitters', 'Gas Cylinder Exchanges', 'Stationery'],
    bannerImage: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'mku_main',
    name: 'Mount Kenya University (MKU Main Campus)',
    shortName: 'MKU Thika',
    type: 'University',
    county: 'Kiambu',
    town: 'Thika Town / General Kago',
    coordinates: { lat: -1.0401, lng: 37.0792 },
    studentPopulation: 42000,
    featuredHubs: ['Section 9 Hostels', 'Thika CBD Tech Street', 'Landless Hostels', 'Makongeni Hub'],
    sampleHostelRentRange: 'KES 5,000 - 12,500 / mo',
    popularServices: ['Pharmacy Revision Books', 'Makongeni Bedsitters', 'Laptop Batteries', 'Food Delivery'],
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'must_main',
    name: 'Meru University of Science and Technology (MUST)',
    shortName: 'MUST Meru',
    type: 'University',
    county: 'Meru',
    town: 'Nchiru, Meru',
    coordinates: { lat: 0.1264, lng: 37.7183 },
    studentPopulation: 15000,
    featuredHubs: ['Nchiru Market Hostels', 'Meru Town CBD Plaza', 'Maua Road Hub'],
    sampleHostelRentRange: 'KES 3,200 - 7,500 / mo',
    popularServices: ['Nchiru Hostels', 'Solar Pumps & PV', 'Fresh Bananas & Potatoes', 'Boda Boda Dispatch'],
    bannerImage: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'nyeri_poly',
    name: 'The Nyeri National Polytechnic',
    shortName: 'Nyeri Poly',
    type: 'National Poly',
    county: 'Nyeri',
    town: 'Nyeri Town',
    coordinates: { lat: -0.4211, lng: 36.9482 },
    studentPopulation: 11000,
    featuredHubs: ['Skuta Hostels', 'Nyeri Town Workshop District', 'Ruringu Stadium Area'],
    sampleHostelRentRange: 'KES 3,000 - 6,800 / mo',
    popularServices: ['Skuta Rooms', 'Plumbing & Building Tools', 'Solar Batteries', 'Printing'],
    bannerImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&auto=format&fit=crop&q=80'
  },

  // --- EASTERN & NORTH EASTERN ---
  {
    id: 'seku_main',
    name: 'South Eastern Kenya University (SEKU)',
    shortName: 'SEKU Kitui',
    type: 'University',
    county: 'Kitui',
    town: 'Kwa Vonza / Kitui',
    coordinates: { lat: -1.3142, lng: 37.7554 },
    studentPopulation: 14000,
    featuredHubs: ['Kwa Vonza Hub Hostels', 'Kitui Town Campus', 'Maniandu Center'],
    sampleHostelRentRange: 'KES 3,000 - 6,500 / mo',
    popularServices: ['Kwa Vonza Hostels', 'Solar Backup Lighting', 'Water Purifiers', 'Boda Services'],
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'garissa_univ',
    name: 'Garissa University',
    shortName: 'Garissa Uni',
    type: 'University',
    county: 'Garissa',
    town: 'Garissa Town',
    coordinates: { lat: -0.4532, lng: 39.6461 },
    studentPopulation: 7500,
    featuredHubs: ['Garissa Town Market', 'Sankuri Road Hub', 'Madina Hostels'],
    sampleHostelRentRange: 'KES 3,500 - 7,500 / mo',
    popularServices: ['Solar Fans', 'Cold Water Storage', 'Camel Milk & Fresh Foods', 'Madina Bedsitters'],
    bannerImage: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'kmtc_eldoret',
    name: 'KMTC Eldoret Campus',
    shortName: 'KMTC Eldoret',
    type: 'Medical Training',
    county: 'Uasin Gishu',
    town: 'Eldoret / MTRH',
    coordinates: { lat: 0.5186, lng: 35.2819 },
    studentPopulation: 6000,
    featuredHubs: ['MTRH Medical Hub', 'Pioneer Hostels', 'Elgon View Annex'],
    sampleHostelRentRange: 'KES 4,500 - 9,000 / mo',
    popularServices: ['Lab Coats', 'Clinical Thermometers', 'Anatomy Guides', 'Hostels Near MTRH'],
    bannerImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'kisumu_poly',
    name: 'The Kisumu National Polytechnic',
    shortName: 'Kisumu Poly',
    type: 'National Poly',
    county: 'Kisumu',
    town: 'Kisumu City',
    coordinates: { lat: -0.0917, lng: 34.7679 },
    studentPopulation: 14000,
    featuredHubs: ['Polytechnic Junction', 'Kondele Tech Center', 'Milimani Outskirts Hostels'],
    sampleHostelRentRange: 'KES 3,800 - 8,200 / mo',
    popularServices: ['Welding Equipment', 'Solar Power Packs', 'Kondele Food Hub', 'Hostels'],
    bannerImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80'
  }
];
