import { HostelBooking } from '../types';

export const INITIAL_HOSTEL_BOOKINGS: HostelBooking[] = [
  {
    id: 'book_juja_101',
    hostelId: 'hostel_juja_havens',
    hostelTitle: 'Juja Havens Executive Modern Bedsitters & 1-Bedrooms',
    landlordId: 'user_landlord_1',
    landlordName: 'Juja Student Havens & Heights',
    studentId: 'user_student_campus',
    studentName: 'Brian Mwangi (Campus 3rd Year)',
    studentEmail: 'brian.mwangi@uonbi.ac.ke',
    studentPhone: '+254 743 112 233',
    campusName: 'JKUAT Main Campus (Gate C)',
    roomType: 'Bedsitter',
    unitNumber: 'Block B - Rm 14',
    moveInDate: '2026-09-01',
    durationMonths: 4,
    monthlyRentKes: 9500,
    holdingDepositKes: 4750,
    totalPaidKes: 4750,
    status: 'confirmed_reserved',
    pesapalTrackingId: 'PESA-RES-8829147',
    receiptNumber: 'ENM-HOSTEL-2026-0041',
    createdAt: '2026-08-15'
  },
  {
    id: 'book_kahawa_202',
    hostelId: 'hostel_kahawa_sukari',
    hostelTitle: 'Kahawa Sukari Heights Luxury 1-Bedroom & Studios',
    landlordId: 'user_landlord_1',
    landlordName: 'Juja Student Havens & Heights',
    studentId: 'user_student_2',
    studentName: 'Faith Wanjiru (Kenyatta University)',
    studentEmail: 'faith.wanjiru@ku.ac.ke',
    studentPhone: '+254 718 456 789',
    campusName: 'Kenyatta University (KU Main)',
    roomType: 'Studio',
    unitNumber: 'Apt 304',
    moveInDate: '2026-09-05',
    durationMonths: 4,
    monthlyRentKes: 14500,
    holdingDepositKes: 7250,
    totalPaidKes: 7250,
    status: 'confirmed_reserved',
    pesapalTrackingId: 'PESA-RES-9931842',
    receiptNumber: 'ENM-HOSTEL-2026-0042',
    createdAt: '2026-08-16'
  }
];
