/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AICategory, EnermindFile } from '../../src/types/index.js';
import { googleDriveService } from './drive.js';
import { geminiService } from './gemini.js';

export interface DocumentAnalysisRequest {
  userId: string;
  fileId: string;
  userExplicitConsent: boolean;
  action: 'SUMMARIZE_NOTES' | 'EXPLAIN_PAST_PAPER' | 'GENERATE_QUIZ' | 'SEMANTIC_SEARCH';
  questionQuery?: string;
  targetLength?: 'BRIEF' | 'DETAILED' | 'EXAM_PREP';
}

export interface DocumentAnalysisResponse {
  success: boolean;
  fileId: string;
  fileName: string;
  action: string;
  extractedTextSnippet?: string;
  aiResult?: string;
  quizItems?: Array<{ question: string; options: string[]; answerIndex: number; explanation: string }>;
  error?: string;
  disclaimer: string;
}

export class DocumentAiPreparationService {
  /**
   * Phase 4 Preparation: Validates explicit user consent and file ownership before any AI interaction
   */
  async processAuthorizedDocument(req: DocumentAnalysisRequest): Promise<DocumentAnalysisResponse> {
    // 1. Mandatory Explicit User Authorization Check
    if (!req.userExplicitConsent) {
      return {
        success: false,
        fileId: req.fileId,
        fileName: 'Unknown',
        action: req.action,
        error: 'Explicit user authorization is required before processing private documents with AI.',
        disclaimer: 'Enermind enforces zero-knowledge defaults. Documents are never processed without explicit opt-in.',
      };
    }

    // 2. File Ownership Verification
    const file = googleDriveService.getFileById(req.userId, req.fileId);
    if (!file) {
      return {
        success: false,
        fileId: req.fileId,
        fileName: 'Unknown',
        action: req.action,
        error: 'Unauthorized or file does not exist in your authorized workspace.',
        disclaimer: 'Enermind verifies Google Drive ownership before every operation.',
      };
    }

    // 3. Document text extraction preparation
    const simulatedExtractedText = `Extracted contents from ${file.name} for course ${file.courseCode || 'Academic Unit'}. Topics: ${file.topic || file.name}`;

    // 4. Delegate to Gemini Service when requested
    if (req.action === 'EXPLAIN_PAST_PAPER') {
      const explanation = await geminiService.explainPastPaper({
        paperTitle: file.name,
        questionText: req.questionQuery || file.sampleQuestion || 'Explain key exam methodologies and breakdown solutions.',
        courseName: file.courseName || file.courseCode || 'Computer Science',
      });

      return {
        success: true,
        fileId: file.id,
        fileName: file.name,
        action: req.action,
        extractedTextSnippet: simulatedExtractedText,
        aiResult: explanation.explanation,
        disclaimer: 'Generated by Gemini 3.7 Flash via user-authorized file gateway.',
      };
    }

    if (req.action === 'SUMMARIZE_NOTES') {
      const res = await geminiService.generateCampusAssistance({
        category: AICategory.ACADEMIC,
        prompt: `Provide a structured academic summary and study cheat sheet for the document "${file.name}" in course "${file.courseCode || 'General'}". Focus on key theorems, formulas, and common exam pitfalls.`,
        userContext: {
          courseName: file.courseName,
          institutionName: file.institutionName,
        },
        hasPrivateVaultAuthorization: true,
      });

      return {
        success: true,
        fileId: file.id,
        fileName: file.name,
        action: req.action,
        extractedTextSnippet: simulatedExtractedText,
        aiResult: res.response,
        disclaimer: 'Generated by Gemini 3.7 Flash via user-authorized file gateway.',
      };
    }

    return {
      success: true,
      fileId: file.id,
      fileName: file.name,
      action: req.action,
      extractedTextSnippet: simulatedExtractedText,
      aiResult: 'Document AI pipeline initialized and prepared for Phase 4 full extraction.',
      disclaimer: 'Enermind zero-knowledge authorization pipeline.',
    };
  }
}

export const documentAiService = new DocumentAiPreparationService();
